### ISSUE TITLE
projecthandler missing ?

### ISSUE THREAD

**Issue by mayank-k-jha** [marmurar/pyamplitude#1]
Still after installation, throws below error. it seems project handler is not even in repo. Please fix this.

---->  from pyamplitude.projectshandler import ProjectsHandler

ImportError: No module named 'pyamplitude.projectshandler'

**Comment by mmmuraro-meli** [comment]
Thank you very much for reporting that issue. Failed completely to notice it was missing. Pushed it and tested, let me know if worked ok.

**Comment by marmurar** [comment]
Thank you very much for reporting this issue. Just pushed projecthandler ,let me know if it worked.

**Comment by mayank-k-jha** [comment]
Thanks for the help. Now it's working very well. :)

**Comment by leuhan** [comment]
Hi! I'm using python 2.7 and I'm getting same error: 

Any idea? Thanks in advance!

**Comment by marmurar** [comment]
Hi ! Just tried with Python 2.7 and worked fine...  May be you can clone the repo and add the .ṕy file with project handler class for a quick fix.

**Comment by leuhan** [comment]
Thank you!

**Comment by yashagarwal93** [comment]
"ModuleNotFoundError: No module named 'pyamplitude.projectshandler'"

after installation I'm getting this error

**Comment by thorep** [comment]
Same here modulenotfound

**Comment by marmurar** [comment]
@thorep, @yashagarwal93 may i ask how are you both installing the package ? tried to use it and did not found the same error. Thanks !
