### ISSUE TITLE
minor documentation update

### ISSUE THREAD

**Issue by gitlech** [marmurar/pyamplitude#3]
Documentation seems not to be 100% accurate:

In **How to use PyAmplitude ?** chapter, code example should be like this:

from pyamplitude.apiresources import ProjectsHandler

bubbleConector = ProjectsHandler(project_name='BubbleWay',
                                  api_key='<api_key>',
                                  secret_key='<secret_key>')

**Comment by marmurar** [comment]
Thanks so much ! Changed the README just a few seconds ago. Let me know if there is anything else !
Mark.
